	switch(level)
	{
	case 1,10,21:
		{
			switch(listitem)
			{
			case 0: InviteSkin[giveplayerid] = 280;
			case 1: InviteSkin[giveplayerid] = 281;
			case 2: InviteSkin[giveplayerid] = 282;
			case 3: InviteSkin[giveplayerid] = 283;
			case 4: InviteSkin[giveplayerid] = 284;
			case 5: InviteSkin[giveplayerid] = 285;
			case 6: InviteSkin[giveplayerid] = 288;
			case 7: InviteSkin[giveplayerid] = 76;
			}
		}
	case 2:
		{
			switch(listitem)
			{
			case 0: InviteSkin[giveplayerid] = 286;
			case 1: InviteSkin[giveplayerid] = 163;
			case 2: InviteSkin[giveplayerid] = 164;
			case 3: InviteSkin[giveplayerid] = 165;
			case 4: InviteSkin[giveplayerid] = 166;
			case 5: InviteSkin[giveplayerid] = 141;
			}
		}
	case 3,19:
		{
			switch(listitem)
			{
			case 0: InviteSkin[giveplayerid] = 287;
			case 1: InviteSkin[giveplayerid] = 191;
			}
		}
	case 4:
		{
			switch(listitem)
			{
			case 0: InviteSkin[giveplayerid] = 70;
			case 1: InviteSkin[giveplayerid] = 274;
			case 2: InviteSkin[giveplayerid] = 275;
			case 3: InviteSkin[giveplayerid] = 276;
			case 4: InviteSkin[giveplayerid] = 219;
			}
		}
	case 5:
		{
			switch(listitem)
			{
			case 0: InviteSkin[giveplayerid] = 223;
			case 1: InviteSkin[giveplayerid] = 124;
			case 2: InviteSkin[giveplayerid] = 113;
			case 3: InviteSkin[giveplayerid] = 214;
			}
		}
	case 6:
		{
			switch(listitem)
			{
			case 0: InviteSkin[giveplayerid] = 120;
			case 1: InviteSkin[giveplayerid] = 123;
			case 2: InviteSkin[giveplayerid] = 169;
			case 3: InviteSkin[giveplayerid] = 186;
			case 4: InviteSkin[giveplayerid] = 118;
			case 5: InviteSkin[giveplayerid] = 117;
			}
		}
	case 7:
		{
			switch(listitem)
			{
			case 0: InviteSkin[giveplayerid] = 57;
			case 1: InviteSkin[giveplayerid] = 150;
			case 2: InviteSkin[giveplayerid] = 98;
			case 3: InviteSkin[giveplayerid] = 187;
			case 4: InviteSkin[giveplayerid] = 147;
			}
		}
	case 11:
		{
			switch(listitem)
			{
			case 0: InviteSkin[giveplayerid] = 59;
			case 1: InviteSkin[giveplayerid] = 172;
			case 2: InviteSkin[giveplayerid] = 189;
			case 3: InviteSkin[giveplayerid] = 240;
			}
		}
	case 12:
		{
			switch(listitem)
			{
			case 0: InviteSkin[giveplayerid] = 102;
			case 1: InviteSkin[giveplayerid] = 103;
			case 2: InviteSkin[giveplayerid] = 104;
			case 3: InviteSkin[giveplayerid] = 195;
			}
		}
	case 13:
		{
			switch(listitem)
			{
			case 0: InviteSkin[giveplayerid] = 108;
			case 1: InviteSkin[giveplayerid] = 109;
			case 2: InviteSkin[giveplayerid] = 110;
			case 3: InviteSkin[giveplayerid] = 190;
			}
		}
	case 14:
		{
			switch(listitem)
			{
			case 0: InviteSkin[giveplayerid] = 112;
			case 1: InviteSkin[giveplayerid] = 111;
			case 2: InviteSkin[giveplayerid] = 125;
			case 3: InviteSkin[giveplayerid] = 272;
			case 4: InviteSkin[giveplayerid] = 214;
			}
		}
	case 15:
		{
			switch(listitem)
			{
			case 0: InviteSkin[giveplayerid] = 105;
			case 1: InviteSkin[giveplayerid] = 106;
			case 2: InviteSkin[giveplayerid] = 107;
			case 3: InviteSkin[giveplayerid] = 269;
			case 4: InviteSkin[giveplayerid] = 270;
			case 5: InviteSkin[giveplayerid] = 271;
			case 6: InviteSkin[giveplayerid] = 56;
			}
		}
	case 16:
		{
			switch(listitem)
			{
			case 0: InviteSkin[giveplayerid] = 250;
			case 1: InviteSkin[giveplayerid] = 261;
			case 2: InviteSkin[giveplayerid] = 211;
			case 3: InviteSkin[giveplayerid] = 217;
			}
		}
	case 17:
		{
			switch(listitem)
			{
			case 0: InviteSkin[giveplayerid] = 114;
			case 1: InviteSkin[giveplayerid] = 115;
			case 2: InviteSkin[giveplayerid] = 116;
			case 3: InviteSkin[giveplayerid] = 41;
			}
		}
	case 18:
		{
			switch(listitem)
			{
			case 0: InviteSkin[giveplayerid] = 173;
			case 1: InviteSkin[giveplayerid] = 174;
			case 2: InviteSkin[giveplayerid] = 175;
			case 3: InviteSkin[giveplayerid] = 226;
			}
		}
	case 23:
		{
			switch(listitem)
			{
			case 0: InviteSkin[giveplayerid] = 185;
			case 1: InviteSkin[giveplayerid] = 186;
			case 2: InviteSkin[giveplayerid] = 250;
			case 3: InviteSkin[giveplayerid] = 295;
			case 4: InviteSkin[giveplayerid] = 294;
			case 5: InviteSkin[giveplayerid] = 12;
			case 6: InviteSkin[giveplayerid] = 40;
			case 7: InviteSkin[giveplayerid] = 12;
			}
		}
	case 24:
		{
			switch(listitem)
			{
			case 0: InviteSkin[giveplayerid] = 60;
			case 1: InviteSkin[giveplayerid] = 47;
			case 2: InviteSkin[giveplayerid] = 217;
			case 3: InviteSkin[giveplayerid] = 67;
			case 4: InviteSkin[giveplayerid] = 240;
			case 5: InviteSkin[giveplayerid] = 170;
			case 6: InviteSkin[giveplayerid] = 29;
			case 7: InviteSkin[giveplayerid] = 11;
			case 8: InviteSkin[giveplayerid] = 91;
			}
		}
	case 25:
		{
			switch(listitem)
			{
			case 0: InviteSkin[giveplayerid] = 76;
			case 1: InviteSkin[giveplayerid] = 285;
			}
		}
	case 26:
		{
			switch(listitem)
			{
			case 0: InviteSkin[giveplayerid] = 17;
			case 1: InviteSkin[giveplayerid] = 216;
			case 2: InviteSkin[giveplayerid] = 227;
			case 3: InviteSkin[giveplayerid] = 287;
			case 4: InviteSkin[giveplayerid] = 265;
			case 5: InviteSkin[giveplayerid] = 70;
			case 6: InviteSkin[giveplayerid] = 12;
			case 7: InviteSkin[giveplayerid] = 208;
			case 8: InviteSkin[giveplayerid] = 295;
			}
		}
	case 27:
		{
			switch(listitem)
			{
			case 0: InviteSkin[giveplayerid] = 295;
			case 1: InviteSkin[giveplayerid] = 191;
			case 2: InviteSkin[giveplayerid] = 255;
			case 3: InviteSkin[giveplayerid] = 61;
			case 4: InviteSkin[giveplayerid] = 287;
			case 5: InviteSkin[giveplayerid] = 17;
			}
		}
	case 28:
		{
			switch(listitem)
			{
			case 0: InviteSkin[giveplayerid] = 100;
			case 1: InviteSkin[giveplayerid] = 181;
			case 2: InviteSkin[giveplayerid] = 254;
			}
		}
	}
	PlayerInfo[giveplayerid][pModel] = InviteSkin[giveplayerid];
	SetPlayerSkin(giveplayerid,InviteSkin[giveplayerid]);
	return true;