	new ttext[24];
	switch(admin)
	{
	case 1: ttext = "Практикант";
	case 2: ttext = "Ст.Практикант";
	case 3: ttext = "Мл.Модератор";
	case 4: ttext = "Модератор";
	case 5: ttext = "Ст.Модератор";
	case 6: ttext = "Гл.Модератор";
	case 7: ttext = "Мл.Администратор";
	case 8: ttext = "Администратор";
	case 9: ttext = "Ст.Администратор";
	case 10: ttext = "Гл.Администратор";
	case 11: ttext = "Спец.Администратор";
	case 12: ttext = "Зам. Основателя";
	case 13: ttext = "Основатель проекта";
	}
	return ttext;