	new ftext[20];
	switch(member)
	{
	case 0: ftext = "Гражданский";
	case 1: ftext = "LSPD";
	case 2: ftext = "FBI";
	case 3: ftext = "Армия Авианосец";
	case 4: ftext = "Мин.Здрав";
	case 5: ftext = "La Cosa Nostra";
	case 6: ftext = "Yakuza";
	case 7: ftext = "Мэрия";
	case 10: ftext = "SFPD";
	case 11: ftext = "Инструкторы";
	case 12: ftext = "Ballas Gang";
	case 13: ftext = "Vagos Gang";
	case 14: ftext = "Russian Mafia";
	case 15: ftext = "Grove Street Gang";
	case 16: ftext = "LS News";
	case 17: ftext = "Aztecas Gang";
	case 18: ftext = "Rifa Gang";
	case 19: ftext = "Зона 51";
	case 21: ftext = "LVPD";
		/*case 23: ftext = "Hitmans";*/
	case 24: ftext = "Street Racers";
	case 25: ftext = "S.W.A.T";
	case 26: ftext = "Правительство";
	case 27: ftext = "Военно Морской Флот";
	case 28: ftext = "Hell’s Angels MC";
	default: ftext = "Гражданский";
	}
	return ftext;