	Capture[playerid][0] = CreatePlayerTextDraw(playerid, 107.000000, 293.000000, "_");
	PlayerTextDrawAlignment(playerid, Capture[playerid][0], 2);
	PlayerTextDrawBackgroundColor(playerid, Capture[playerid][0], 255);
	PlayerTextDrawFont(playerid, Capture[playerid][0], 1);
	PlayerTextDrawLetterSize(playerid, Capture[playerid][0], 1.120000, 3.200000);
	PlayerTextDrawColor(playerid, Capture[playerid][0], -1);
	PlayerTextDrawSetOutline(playerid, Capture[playerid][0], 0);
	PlayerTextDrawSetProportional(playerid, Capture[playerid][0], 1);
	PlayerTextDrawSetShadow(playerid, Capture[playerid][0], 1);
	PlayerTextDrawUseBox(playerid, Capture[playerid][0], 1);
	PlayerTextDrawBoxColor(playerid, Capture[playerid][0], 112);
	PlayerTextDrawTextSize(playerid, Capture[playerid][0], 43.000000, 206.000000);
	PlayerTextDrawSetSelectable(playerid, Capture[playerid][0], 0);

	Capture[playerid][1] = CreatePlayerTextDraw(playerid, 5.000000, 292.000000, "_");//time
	PlayerTextDrawBackgroundColor(playerid, Capture[playerid][1], 255);
	PlayerTextDrawFont(playerid, Capture[playerid][1], 1);
	PlayerTextDrawLetterSize(playerid, Capture[playerid][1], 0.490000, 1.000000);
	PlayerTextDrawColor(playerid, Capture[playerid][1], 96492799);
	PlayerTextDrawSetOutline(playerid, Capture[playerid][1], 1);
	PlayerTextDrawSetProportional(playerid, Capture[playerid][1], 1);
	PlayerTextDrawSetSelectable(playerid, Capture[playerid][1], 0);

	Capture[playerid][2] = CreatePlayerTextDraw(playerid, 5.000000, 302.000000, "_");//banda napad
	PlayerTextDrawBackgroundColor(playerid, Capture[playerid][2], 255);
	PlayerTextDrawFont(playerid, Capture[playerid][2], 1);
	PlayerTextDrawLetterSize(playerid, Capture[playerid][2], 0.480000, 1.000000);
	PlayerTextDrawColor(playerid, Capture[playerid][2], -1);
	PlayerTextDrawSetOutline(playerid, Capture[playerid][2], 1);
	PlayerTextDrawSetProportional(playerid, Capture[playerid][2], 1);
	PlayerTextDrawSetSelectable(playerid, Capture[playerid][2], 0);

	Capture[playerid][3] = CreatePlayerTextDraw(playerid, 5.000000, 312.000000, "_");//banda vlad
	PlayerTextDrawBackgroundColor(playerid, Capture[playerid][3], 255);
	PlayerTextDrawFont(playerid, Capture[playerid][3], 1);
	PlayerTextDrawLetterSize(playerid, Capture[playerid][3], 0.480000, 1.000000);
	PlayerTextDrawColor(playerid, Capture[playerid][3], -1);
	PlayerTextDrawSetOutline(playerid, Capture[playerid][3], 1);
	PlayerTextDrawSetProportional(playerid, Capture[playerid][3], 1);
	PlayerTextDrawSetSelectable(playerid, Capture[playerid][3], 0);

	Bizwar[playerid][0] = CreatePlayerTextDraw(playerid, 5.000000, 292.000000, "_");//time
	PlayerTextDrawBackgroundColor(playerid, Bizwar[playerid][0], 255);
	PlayerTextDrawFont(playerid, Bizwar[playerid][0], 1);
	PlayerTextDrawLetterSize(playerid, Bizwar[playerid][0], 0.490000, 1.000000);
	PlayerTextDrawColor(playerid, Bizwar[playerid][0], 96492799);
	PlayerTextDrawSetOutline(playerid, Bizwar[playerid][0], 1);
	PlayerTextDrawSetProportional(playerid, Bizwar[playerid][0], 1);
	PlayerTextDrawSetSelectable(playerid, Bizwar[playerid][0], 0);

	Bizwar[playerid][1] = CreatePlayerTextDraw(playerid, 5.000000, 302.000000, "_");//banda napad
	PlayerTextDrawBackgroundColor(playerid, Bizwar[playerid][1], 255);
	PlayerTextDrawFont(playerid, Bizwar[playerid][1], 1);
	PlayerTextDrawLetterSize(playerid, Bizwar[playerid][1], 0.480000, 1.000000);
	PlayerTextDrawColor(playerid, Bizwar[playerid][1], -1);
	PlayerTextDrawSetOutline(playerid, Bizwar[playerid][1], 1);
	PlayerTextDrawSetProportional(playerid, Bizwar[playerid][1], 1);
	PlayerTextDrawSetSelectable(playerid, Bizwar[playerid][1], 0);

	Bizwar[playerid][2] = CreatePlayerTextDraw(playerid, 5.000000, 312.000000, "_");//banda vlad
	PlayerTextDrawBackgroundColor(playerid, Bizwar[playerid][2], 255);
	PlayerTextDrawFont(playerid, Bizwar[playerid][2], 1);
	PlayerTextDrawLetterSize(playerid, Bizwar[playerid][2], 0.480000, 1.000000);
	PlayerTextDrawColor(playerid, Bizwar[playerid][2], -1);
	PlayerTextDrawSetOutline(playerid, Bizwar[playerid][2], 1);
	PlayerTextDrawSetProportional(playerid, Bizwar[playerid][2], 1);
	PlayerTextDrawSetSelectable(playerid, Bizwar[playerid][2], 0);